highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
baseurl: "/magpie-site"
url: "https://magpie-ea.github.io/magpie-site"
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
